/* import Elysia, { t } from "elysia";
import { addWishlistItem, getUser, isAdmin, renderWishlist } from "../handlers";
import { AddEditModal } from "../views/components/modals/AddEditModal";
import { ErrorModal } from "../views/components/modals/ErrorModal";
import { emitWishlistRefreshEvent } from ".";

const wishlistRoutes = (app: Elysia) => app
	.group('/wishlist', (app) => app
		.get('/add', async ({ set, cookie }) => {
			set.headers['Content-Type'] = 'text/html; charset=utf8';
			return await AddEditModal({admin: isAdmin(cookie.jellyfinId as unknown as string ?? '')});
		})
		.post('/add', async ({ set, body, cookie }) => {
			try{
				const user = await getUser(cookie.jellyfinId as unknown as string);

				await addWishlistItem(body);

				emitWishlistRefreshEvent(await renderWishlist(user));
			}catch(e: any){
				console.error(e);
				set.headers['Content-Type'] = 'text/html; charset=utf8';
				set.status = 500;
				return await ErrorModal(e.message);
			}

			return '';
		}, {
			body: t.Object({
				//id - generated by database
				//status - generated by database, set later
				type: t.Numeric(),
				name: t.String(),
				poster: t.String(),
				createdBy: t.String(),
				//createdAt - generated by database
				year: t.Numeric(),
				imdbId: t.Optional(t.String()),
				tmdbId: t.Optional(t.String()),
				tvdbId: t.Optional(t.String())
			})
		})
	)

export default wishlistRoutes; */