import Elysia, { t } from "elysia";
import { addWishlistItem, renderWishlist } from "../handlers";
import { AddModal } from "../views/components/modals/AddModal";
import { ErrorModal } from "../views/components/modals/ErrorModal";
import { emitWishlistRefreshEvent } from ".";

const wishlistRoutes = (app: Elysia) => app
	.group('/wishlist', (app) => app
		.get('/add', async ({ set }) => {
			set.headers['Content-Type'] = 'text/html; charset=utf8';
			return await AddModal();
		})
		.post('/add', async ({ set, body }) => {
			try{
				await addWishlistItem(body);
				emitWishlistRefreshEvent(await renderWishlist());
			}catch(e: any){
				console.error(e);
				set.headers['Content-Type'] = 'text/html; charset=utf8';
				set.status = 500;
				return await ErrorModal(e.message);
			}

			return '';
		}, {
			body: t.Object({
				//id - generated by database
				//status - generated by database, set later
				type: t.Numeric(),
				name: t.String(),
				poster: t.String(),
				createdBy: t.String(),
				//createdAt - generated by database
				year: t.Numeric(),
				imdbId: t.Optional(t.String()),
				tmdbId: t.Optional(t.String()),
				tvdbId: t.Optional(t.String())
			})
		})
	)

export default wishlistRoutes;